# GoReleaser configuration for AutoNode
# See: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: autonode
    main: ./cmd/autonode
    binary: autonode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore arm64 for windows (not commonly used)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: autonode
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - install.sh
      - uninstall.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'README'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: matutetandil
    name: autonode
  draft: false
  prerelease: auto
  name_template: "AutoNode {{.Version}}"
  header: |
    ## AutoNode {{.Version}}

    Automatic Node.js version switching for your projects.

    ### Installation

    **One-line install:**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/matutetandil/autonode/main/install.sh | bash
    ```

    **Manual install:** Download the binary for your platform below.
